#!/bin/bash
#
# flashesp.sh — Compile and flash ESPPIC-V2 firmware to ESP32
# Requires: install.sh to have been run first
# Designed for Windows Git Bash
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$SCRIPT_DIR/tools"
ARDUINO_CLI="$INSTALL_DIR/arduino-cli"
SKETCH_DIR="$SCRIPT_DIR/esppic"
FQBN="esp32:esp32:esp32"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

echo ""
echo "=========================================="
echo "  ESPPIC-V2 — Flash ESP32 Firmware"
echo "=========================================="
echo ""

# ------------------------------------------------------------------
# Verify toolchain
# ------------------------------------------------------------------
if [[ -f "$ARDUINO_CLI.exe" ]]; then
    ARDUINO_CLI="$ARDUINO_CLI.exe"
fi

if [[ ! -f "$ARDUINO_CLI" ]]; then
    fail "Arduino CLI not found. Run ./install.sh first."
fi

if ! "$ARDUINO_CLI" core list 2>/dev/null | grep -q "esp32:esp32"; then
    fail "ESP32 board support not installed. Run ./install.sh first."
fi

ok "Toolchain verified"

# ------------------------------------------------------------------
# Detect ESP32 on USB
# ------------------------------------------------------------------
info "Scanning for ESP32 on USB..."
echo ""
echo "  Make sure your ESP32 DevKit is plugged in via USB."
echo ""

detect_port() {
    # Arduino CLI board list, look for esp32 or CP210x or CH340 or serial ports
    local ports
    ports=$("$ARDUINO_CLI" board list 2>/dev/null | grep -iE "serial|cp210|ch340|esp32|usb" | head -20)
    if [[ -z "$ports" ]]; then
        # Fallback: list all serial ports
        ports=$("$ARDUINO_CLI" board list 2>/dev/null | grep -vE "^Port|^$|^No " | head -20)
    fi
    echo "$ports"
}

PORTS=$(detect_port)

if [[ -z "$PORTS" ]]; then
    echo ""
    warn "No serial ports detected!"
    echo ""
    echo "  Possible fixes:"
    echo "    - Plug in the ESP32 via USB"
    echo "    - Install CP210x or CH340 USB driver"
    echo "    - Try a different USB cable (some are charge-only)"
    echo ""
    read -rp "  Press Enter to retry, or Ctrl+C to exit... "
    PORTS=$(detect_port)
    if [[ -z "$PORTS" ]]; then
        fail "Still no serial ports detected."
    fi
fi

echo "  Detected ports:"
echo "  ───────────────"
echo "$PORTS" | while IFS= read -r line; do echo "    $line"; done
echo ""

# Extract just the port names (first column)
PORT_LIST=()
while IFS= read -r line; do
    port=$(echo "$line" | awk '{print $1}')
    if [[ -n "$port" ]]; then
        PORT_LIST+=("$port")
    fi
done <<< "$PORTS"

if [[ ${#PORT_LIST[@]} -eq 0 ]]; then
    fail "Could not parse any serial ports."
fi

if [[ ${#PORT_LIST[@]} -eq 1 ]]; then
    SELECTED_PORT="${PORT_LIST[0]}"
    info "Auto-selected port: $SELECTED_PORT"
else
    echo "  Multiple ports found. Select your ESP32 port:"
    for i in "${!PORT_LIST[@]}"; do
        echo "    [$((i+1))] ${PORT_LIST[$i]}"
    done
    echo ""
    read -rp "  Enter number [1-${#PORT_LIST[@]}]: " choice
    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#PORT_LIST[@]} )); then
        SELECTED_PORT="${PORT_LIST[$((choice-1))]}"
    else
        fail "Invalid selection."
    fi
fi

ok "Using port: $SELECTED_PORT"
echo ""

# ------------------------------------------------------------------
# WiFi credentials
# ------------------------------------------------------------------
echo "  Enter your WiFi credentials so the ESP32 can connect"
echo "  to your network automatically after flashing."
echo ""
read -rp "  WiFi SSID: " WIFI_SSID
if [[ -z "$WIFI_SSID" ]]; then
    fail "SSID cannot be empty."
fi
read -rsp "  WiFi Password: " WIFI_PASS
echo ""
echo ""

# Write credentials to a header file included by the firmware
cat > "$SKETCH_DIR/wifi_config.h" <<WIFICFG
// Auto-generated by flashesp.sh — do not edit manually
#define WIFI_SSID "${WIFI_SSID//\"/\\\"}"
#define WIFI_PASS "${WIFI_PASS//\"/\\\"}"
WIFICFG

ok "WiFi credentials saved for compilation"
echo ""

# ------------------------------------------------------------------
# Compile
# ------------------------------------------------------------------
info "Compiling ESPPIC-V2 firmware..."
echo "  Board: $FQBN"
echo "  Sketch: $SKETCH_DIR"
echo ""

"$ARDUINO_CLI" compile \
    --fqbn "$FQBN" \
    --build-property "build.partitions=default" \
    "$SKETCH_DIR" || fail "Compilation failed!"

ok "Compilation successful"

# ------------------------------------------------------------------
# Upload
# ------------------------------------------------------------------
echo ""
info "Uploading firmware to ESP32..."
echo ""
echo "  If the upload stalls, hold the BOOT button on your ESP32"
echo "  when you see 'Connecting...' and release after upload starts."
echo ""

"$ARDUINO_CLI" upload \
    --fqbn "$FQBN" \
    --port "$SELECTED_PORT" \
    "$SKETCH_DIR" || fail "Upload failed! Try holding the BOOT button during upload."

ok "Firmware uploaded successfully!"

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
# ------------------------------------------------------------------
# Wait for ESP32 to connect and report its IP
# ------------------------------------------------------------------
echo ""
info "Waiting for ESP32 to connect to WiFi..."
echo "  (monitoring serial output for IP address)"
echo ""

ESP_IP=""
SERIAL_TIMEOUT=30
while (( SERIAL_TIMEOUT > 0 )); do
    LINE=$(timeout 2 "$ARDUINO_CLI" monitor --port "$SELECTED_PORT" --config baudrate=115200 --raw 2>/dev/null | head -20 || true)
    if [[ -n "$LINE" ]]; then
        FOUND_IP=$(echo "$LINE" | grep -oE 'IP=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)' | head -1 | cut -d= -f2)
        if [[ -n "$FOUND_IP" ]]; then
            ESP_IP="$FOUND_IP"
            break
        fi
    fi
    SERIAL_TIMEOUT=$((SERIAL_TIMEOUT - 2))
done

if [[ -z "$ESP_IP" ]]; then
    warn "Could not auto-detect ESP32 IP from serial."
    echo ""
    echo "  The ESP32 should be connecting to: $WIFI_SSID"
    echo "  Check your router's DHCP table for the IP."
    echo ""
    read -rp "  Enter ESP32 IP manually (or press Enter to skip): " ESP_IP
fi

# Save config for flashbmc.sh
if [[ -n "$ESP_IP" ]]; then
    echo "$ESP_IP" > "$SCRIPT_DIR/.esp32_ip"
    ok "ESP32 IP: $ESP_IP (saved for flashbmc.sh)"
fi

echo ""
echo "=========================================="
echo -e "  ${GREEN}ESP32 flashed successfully!${NC}"
echo ""
echo "  The ESP32 will now reboot and connect to: $WIFI_SSID"
if [[ -n "$ESP_IP" ]]; then
echo ""
echo "  Web UI:       http://$ESP_IP/i.html"
echo "  File Manager: http://$ESP_IP/fm"
fi
echo ""
echo "  If WiFi fails, the ESP32 will start an 'ESPPIC' hotspot."
echo "  Connect to it and open http://192.168.4.1 to reconfigure."
echo ""
echo "  Next step: ./flashbmc.sh"
echo "=========================================="
echo ""
