
// wifi_config.h is auto-generated by flashesp.sh with WIFI_SSID and WIFI_PASS
// If not present, the ESP32 will fall back to AP mode for configuration
#if __has_include("wifi_config.h")
  #include "wifi_config.h"
#endif

void ConnectToWifi() {
#ifdef WIFI_SSID
  Serial.printf("Connecting to WiFi: %s\n", WIFI_SSID);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
#else
  Serial.println("Connecting to wifi using saved credentials...");
  WiFi.mode(WIFI_STA);
  WiFi.begin();
#endif
  int timeout=60;
  while(timeout-- && WiFi.status()!=WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  if (WiFi.status()==WL_CONNECTED) {
    Serial.print("Successfully connected. IP=");
    Serial.println(WiFi.localIP());
    return;
  }
  Serial.print("Starting soft-AP for configuration... ");
  WiFi.mode(WIFI_AP);
  Serial.println(WiFi.softAP("ESPPIC") ? "Ready" : "Failed!");
  Serial.print("AP IP address: ");
  Serial.println(WiFi.softAPIP());

  server.on("/",HTTP_POST,[]() {
        String content = "<!DOCTYPE HTML><html><pre>ESP32 Setup\n-------------\n";
        content += "Storing credentials and rebooting.\nPlease re-connect to your usual WiFi network.</pre>";
        content += "</html>";
        server.send(200, "text/html", content);

        Serial.printf("ssid=%s\n",server.arg("ssid").c_str());
        Serial.printf("pw=%s\n",server.arg("pw").c_str());
        WiFi.disconnect();
        delay(100);
        WiFi.mode(WIFI_STA);
        WiFi.begin(server.arg("ssid").c_str(),server.arg("pw").c_str());

  int timeout=60;
  while(timeout-- && WiFi.status()!=WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  if (WiFi.status()==WL_CONNECTED) {
    Serial.print("Successfully connected. IP=");
    Serial.println(WiFi.localIP());
    return;
  }
  Serial.println("Failed to connect with provided credentials!");
  });

  server.on("/", []() {
        String content = "<!DOCTYPE HTML><html><pre>ESPPIC WiFi Setup\n-----------------\n";
        content += "<form method='POST' action=''>SSID:    <input name='ssid' />\nPassword:<input name='pw' type='password' />\n<input type='submit' value='Connect' /></form></pre>";
        content += "</html>";
        server.send(200, "text/html", content);
  });
  server.begin();
  while (1) {
    server.handleClient();
    delay(1);
  }
}

